### ISSUE TITLE
Point config.js and proxy to try it live webmap id and services

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/executive-dashboard#35]
Point config.js and proxy to try it live webmap id and services

- [x] config.js updated to use tryitlive
- [x] proxy file references to dev server removed

**Comment by lindsayking** [comment]
@LindsayThomas 

* config.js - no updates needed to either configLG.js or config.js.  Both reference try it live.
* proxy.config - updated to remove http://arcgis-tenone2012-1974758903.us-west-1.elb.amazonaws.com/arcgis/rest/services
